### PR TITLE
A really small first Pull Requests to see if you're open of the idea.

### PR DESCRIPTION
**Pull request by Sdwz**
Hi,

I'm sorry to say I've seen some unoptimized code in adaptors lately, and I'm willing to help if you guys are open to this.

This is a sample of what I think is an optimization of the current code base. I'm obviously kinda here to discuss as github open a brand new channel of communication with you guys that we kinda never had before.

I've seen many things to do, and if you're open to Pull Requests, I can do a lot more.
For instance, I think my next target would be the containsKey method complete eradication where possible, aka when a get is called right afterwards. (containsKey and get both loop, there is no way it's not ressources consuming, and it's really scattered all over the code)

I hope we can discuss all this and get those adaptor top notch !

Of course, my approach might be wrong based on some standard I don't know, but let's discuss it, again :)

Cheers :)

### CODE REVIEW

**Comment by PapaJoltOmega** [comment]
On the upside this is a good way to start with a project.

On the downside the formatting is a bit off, and it is not
clear that this change is a meaningful speedup.

Thank you,
PJ

**Comment by ghost** [comment]
Hi,

If you can share your formatter, it would actually help a lot getting things proper. I could share a better cleanup for review, it's actually cluttered currently and I didn't put more because of that. (I would use mine for coding though :D)

I have an AD available with 70k entries (customer one actually), I can attach jprofiler to it and see how it goes, but a get on a map can be ressource consuming, especially for big one. For memory, it would dropping all those map and more :| a bit longer but both are worse it, even if it sounds like micro optimization In this particular case. I'm been working on a game emulator for the past 9 years and you really feel the difference when things get huge.

Overuse of the containsKey and improper method is really a good sample in term of ressource stress you apply. 

E.g : 

https://github.com/googlegsa/activedirectory/blob/a9818da94f01bd3d004c528fd2da1682f979570e/src/com/google/enterprise/adaptor/ad/AdAdaptor.java#L653

get, get, remove.

final Set<String> oldEntityValues = primaryMembers.remove(oldEntity);
if (null != oldEntityValues)
{
      primaryMembers.put(e, oldEntityValues);
}

You just made 3 loop on the key table, just one.

Well again that's just a thought. It might not matter for such scale that much.

**Comment by PapaJoltOmega** [comment]
Hi Sdw,

I do not personally use a formatter.  A search for 
"formatter for google java style guide" yields seemingly
good results for Eclipse and Intellij.

Running profiler on a 70K entry setup, then seeing the
hotspots, then addressing those, is, IMO, a scientific
approach to optimization. Yes, the loops are likely to
be more performent with your suggestion, but with
all the network traffic, locks, and other operations are
you sure it will be noticable per run?

I don't want to loose sight that I appreciate you making
changes, and I believe the size of this change is a nice
introduction.

Also, have you, or your company accepted Google's
contributor agreement?

Thank you

**Comment by ghost** [comment]
Hi,

Yes the CLA has been signed by my company something like 2 years ago.

I'm gonna start monitoring and doing changes next week as this week is busy... testing something ;)

Cheers

**Pull request closed without merging**
